services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: go run main.go
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST='db'
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
    container_name: postgres_alpine
